spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sampledb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sampleuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:samplepass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
